### ISSUE TITLE
Items are despawning on Equipment (With Transmog Errormessage)

### ISSUE THREAD

**Issue by Arebs** [mxswat/pz-transmog-definitive-edition#1]
Hey there, 
Me and my friends encountered a Issue today, that some of our clothing despawned on equiping them. After search through the logs, it seems that the transmog mod seemed to throw an error everytime we encountered this issue. I don't know if this is necessary a problem with this mod, but I don't any other clues. It happend with vanilla equipment (as example: digital watches) and with modded equipment. A file with the Serversettings is attached and the stack trace is here:

STACK TRACE
-----------------------------------------
function: forceUpdateClothing -- file: TransmogDE.lua line # 305 | MOD: Transmog Definitive Edition
function: setItemToDefault -- file: TransmogDE.lua line # 298 | MOD: Transmog Definitive Edition
function: createItem -- file: ISClothingExtraAction.lua line # 16 | MOD: Transmog Definitive Edition
function: perform -- file: ISClothingExtraAction.lua line # 52 | Vanilla

ERROR: General     , 1685733750158> 38.542.981.308> ExceptionLogger.logException>y
ERROR: General     , 1685733750158> 38.542.981.308> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: getItemById of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1782)
	at se.krka.kahlua.integration.LuaCaller.pcall(LuaCaller.java:85)
	at zombie.characters.CharacterTimedActions.LuaTimedActionNew.perform(LuaTimedActionNew.java:104)
	at zombie.characters.IsoGameCharacter.updateInternal(IsoGameCharacter.java:9726)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.characters.IsoGameCharacter.update(IsoGameCharacter.java:9464)
	at zombie.characters.IsoPlayer.updateInternal1(IsoPlayer.java:1943)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.characters.IsoPlayer.update(IsoPlayer.java:1924)
	at zombie.MovingObjectUpdateSchedulerUpdateBucket.update(MovingObjectUpdateSchedulerUpdateBucket.java:79)
	at zombie.MovingObjectUpdateScheduler.update(MovingObjectUpdateScheduler.java:145)
	at zombie.iso.IsoCell.ProcessObjects(IsoCell.java:2955)
	at zombie.iso.IsoCell.updateInternal(IsoCell.java:5750)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoCell.update(IsoCell.java:5696)
	at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3499)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoWorld.update(IsoWorld.java:3427)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1617)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:298)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:681)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
	
	
	
[Serversettings.txt](https://github.com/mxswat/pz-transmog-definitive-edition/files/11638357/Serversettings.txt)

**Comment by visua0** [comment]
Encountered the same issue. It seems to happen with all clothing that has an option when wearing it, like baseball caps, watches, fanny packs, hoodies, etc.

**Comment by mxswat** [comment]
I fixed this two days ago. Is this still happening?

**Comment by Arebs** [comment]
I just tried it and its not happening for me anymore. Thanks for the fix! 😄

**Comment by mxswat** [comment]
Great! You are welcome!
